---
- name: Install
  ansible.builtin.package:
    name: rsyslog
    state: present
  become: true
  become_user: root

- name: Configure server to include /etc/rsyslog.d/*.conf
  ansible.builtin.lineinfile:
    dest: /etc/rsyslog.conf
    line: "$IncludeConfig /etc/rsyslog.d/*.conf"
  notify: Restart rsyslog-server
  become: true
  become_user: root

- name: Create settings directory
  ansible.builtin.file:
    path: /etc/rsyslog.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true
  become_user: root

- name: Customize settings for syslog
  ansible.builtin.template:
    src: ansible_configured.jinja2
    dest: /etc/rsyslog.d/ansible_configured.conf
    owner: root
    group: root
    mode: "0660"
  notify: Restart rsyslog-server
  become: true
  become_user: root

- name: Remove old config entry
  ansible.builtin.lineinfile:
    dest: /etc/rsyslog.conf
    regexp: "@{{ syslog_server_address }}:{{ syslog_server_port }}"
    state: absent
  notify: Restart rsyslog-server
  become: true
  become_user: root
